### PR TITLE
Refactor .secrets and .configs

### PR DESCRIPTION
**Pull request by osddeitf**
- Allow multikey ConfigMap and Secret
- More compatible with docker-compose
- Prerequisite for implement "mount secret as env"
- Remove support for extra key .subPath mount config/secret options

### CODE REVIEW

**Comment by osddeitf** [comment]
As previous implementation create one **secret** with **singlekey** for each `secrets.XXX`, I don't think it's necessary to mount as directory anyway, and there's should be minor change:
```yaml
secrets:
- source: some_secret_key
  target: /etc
```
to
```yaml
secrets:
- source: some_secret_key
  target: /etc/some_secret_key
```
and it's more intuitive this way, like docker-compose `.target` is name of file, not folder.
For external secret, e.g. ones which generated by **cert-manager**, it's may be more convenient to mount both `tls.crt` and `tls.key` keys, but less intuitive.
I'm thinking a way to implement support for mount multikey external secret to folder, but it's may take time, maybe in the future releases.

As for motivation of this refactor, I think it's better to group related `configs`/`secrets` to multikey `ConfigMap`/`Secret`. 
Further more, I'm planning to implement support for mounting **secret** as **container's environment**, for more secure, with fully compatible with docker-compose file:

> Environment variables with only a key are resolved to their values on the machine Compose is running on, which can be helpful for secret or host-specific values.

But Kubernetes `Secret` name cannot contains **uppercase alphanumeric characters**, but environment variables, so as revert `secrets.XXX` to a **key** (uppercase allowed) in a `Secret` resource make sense.

**Comment by linktohack** [comment]
Have a look at https://github.com/linktohack/helm-stack/blob/master/docker-compose-kubernetes-dashboard.yaml. What do you think? How can we deploy this kind of stack?

**Comment by osddeitf** [comment]
> I'm thinking a way to implement support for mount multikey external secret to folder

**Comment by osddeitf** [comment]
> I'm thinking a way to implement support for mount multikey external secret to folder

As I pointed out earlier, and in your case, it's external secret.
My solution is just mount external secret without `.name` as folder, which can fix this issue.

**Comment by linktohack** [comment]
I don't agree, it's a part of the stack and should be removed if we remove the stack. Even if I want it to be separated, how to deploy these kind of secrets?

**Comment by osddeitf** [comment]
Here are resources I've generated using previous version:
`helm template a link/stack --version=1.8.6 -f docker-compose-kubernetes-dashboard.yaml`
```yaml
---
# Source: stack/templates/stack.yml
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-dashboard-certs
type: Opaque
---
# Source: stack/templates/stack.yml
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-dashboard-csrf
type: Opaque
---
# Source: stack/templates/stack.yml
apiVersion: v1
data:
  auth: UkVEQUNURUQ=
kind: Secret
metadata:
  name: kubernetes-dashboard-default-basic-auth
type: Opaque
---
# Source: stack/templates/stack.yml
apiVersion: v1
kind: Service
metadata:
  name: dashboard-metrics-scraper
spec:
  ports:
  - name: tcp-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    service: dashboard-metrics-scraper
  type: ClusterIP
---
# Source: stack/templates/stack.yml
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
spec:
  ports:
  - name: tcp-8443
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    service: kubernetes-dashboard
  type: ClusterIP
---
# Source: stack/templates/stack.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-metrics-scraper
spec:
  selector:
    matchLabels:
      service: dashboard-metrics-scraper
  template:
    metadata:
      labels:
        service: dashboard-metrics-scraper
    spec:
      containers:
      - image: kubernetesui/metrics-scraper:v1.0.1
        name: dashboard-metrics-scraper
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume2
      serviceAccountName: kubernetes-dashboard
      volumes:
      - emptyDir: {}
        name: tmp-volume2
---
# Source: stack/templates/stack.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-dashboard
spec:
  selector:
    matchLabels:
      service: kubernetes-dashboard
  template:
    metadata:
      labels:
        service: kubernetes-dashboard
    spec:
      containers:
      - args:
        - --auto-generate-certificates
        - --namespace=kubernetes-dashboard
        - --enable-skip-login
        image: kubernetesui/dashboard:v2.0.0-beta8
        imagePullPolicy: Always
        name: kubernetes-dashboard
        volumeMounts:
        - mountPath: /certs
          name: kubernetes-dashboard-certs
        - mountPath: /tmp
          name: tmp-volume1
      serviceAccountName: kubernetes-dashboard
      volumes:
      - name: kubernetes-dashboard-certs
        secret:
          secretName: kubernetes-dashboard-certs
      - emptyDir: {}
        name: tmp-volume1
---
# Source: stack/templates/stack.yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-realm: traefik
    ingress.kubernetes.io/auth-remove-header: "true"
    ingress.kubernetes.io/auth-secret: kubernetes-dashboard-default-basic-auth
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/protocol: https
  name: kubernetes-dashboard-default
spec:
  rules:
  - host: REDACTED
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: tcp-8443
        path: /
```
What's the point of creating "empty" secrets `kubernetes-dashboard-certs` and `kubernetes-dashboard-csrf`?
Are you missing `.secrets.XXX.data` or `.secrets.XXX.stringData`? If not, then they're created outside this (docker-compose-kubernetes-dashboard.yaml) stack, so they're essentially *external secrets*.

**Comment by osddeitf** [comment]
Can you make an example scenario for this?
> Even if I want it to be separated, how to deploy these kind of secrets?

**Comment by linktohack** [comment]
Because they're directory. In the above example:

- `kubernetes-dashboard` is the consumer, it looks for the data from files inside the (seems to be empty but really not) secret.
- `dashboard-metrics-scraper` is the producer, it scrap the metric and feed into (multi key/values or  file/contents) in the secret.

**Comment by osddeitf** [comment]
> dashboard-metrics-scraper is the producer, it scrap the metric and feed into (multi key/values or file/contents) in the secret.

Does `dashboard-metrics-scraper` create/modify secret via ServiceAccount? If so, I think it's just implementation details.
So for best practice, I don't think we should create this secret manually, as it's may change in different releases of `kubernetes-dashboard`.

Anyway, the better is to make a separate namespace for `kubernetes-dashboard`, this way, when you want clean-up, just toss the namespace away. Never mind deleting **persistent volume** (if any), if you want to keep data (may be for future re-deploy), it'll make sense to keep created **secrets** as well.

**Comment by linktohack** [comment]
Just let me mount the the secret as a directory if needed. If it ain't broke, don't fix it.

**Pull request merged**
